apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    spec:
      containers:
      - name: hello-world-container
        image: example.com/hello-world
        imagePullPolicy: IfNotPresent
        env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: hello-world-secret
              key: MESSAGE
        command: ["echo", "$(MESSAGE)"]
      restartPolicy: Never
